#pragma once

namespace KEY_WORDS
{
	constexpr char RESOLUTION[] = "RESOLUTION";
	constexpr char CLUSTERTOLERANCE[] = "CLUSTERTOLERANCE";
	constexpr char MINCLUSTERSIZE[] = "MINCLUSTERSIZE";
	constexpr char  MAXCLUSTERSIZE[] = "MAXCLUSTERSIZE";
	constexpr char  ENABLE_COLOR_TEST[] = "ENABLE_COLOR_TEST";
	constexpr char  COLOR_TEST_MODE[] = "COLOR_TEST_MODE";
	constexpr char  COLOR_TEST_THRESHOLD[] = "COLOR_TEST_THRESHOLD";
	constexpr char  ENABLE_GROUND_TEST[] = "ENABLE_GROUND_TEST";
	constexpr char  GROUND_TEST_THRESHOLD[] = "GROUND_TEST_THRESHOLD";
	constexpr char  ENABLE_NORMAL_TEST[] = "ENABLE_NORMAL_TEST";
	constexpr char  SEARCH_RADIUS[] = "SEARCH_RADIUS";
	constexpr char  POINT_SHOW_SIZE[] = "POINT_SHOW_SIZE";
	constexpr char  OUTLIER_MEAN_KNN_NUMBER[] = "OUTLIER_MEAN_KNN_NUMBER";
	constexpr char  OUTLIER_STD_MULTIPLE_THRESHOLD[] = "OUTLIER_STD_MULTIPLE_THRESHOLD";
	constexpr char  EXCUTEAREA_EXPAND_RATIO[] = "EXCUTEAREA_EXPAND_RATIO";
}